Repository CMU-313/nodebb-f24-team-tbd-1, pull requests merged in 2024-10, with the labels that each got.

#29 Add API Route and Handler For Topic Claim Button
  public/openapi/components/schemas/TopicObject.yaml
  public/src/client/topic.js
  public/src/client/topic/threadTools.js
  src/api/topics.js
  src/controllers/topics.js
  src/controllers/write/topics.js
  src/routes/write/topics.js
Labels: bug

#38 Revert "Revert " Add API Route and Handler For Topic Claim Button""
  public/openapi/components/schemas/TopicObject.yaml
  public/src/client/topic.js
  public/src/client/topic/threadTools.js
  src/api/topics.js
  src/controllers/topics.js
  src/controllers/write/topics.js
  src/routes/write/topics.js
Labels: bug

#34 Routes and Controllers for the new Additonal Information Page
  install/data/navigation.json
  plugin.json
  public/openapi/read.yaml
  public/openapi/read/admin/additional-info.yaml
  src/controllers/additional-info.js
  src/controllers/index.js
  src/middleware/index.js
  src/routes/api.js
  src/routes/index.js
  src/routes/user.js
  test/controllers-admin.js
  test/controllers.js
Labels: enhancement

#40 Add User Guide Claim Button
  UserGuide.md
Labels: documentation

#32 Adding logic to sort the posts by popularity. Still need to be tested
  src/categories/topics.js
  src/controllers/category.js
  src/views/admin/settings/post.tpl
Labels: bug

#49 JScent Test File Integration
  test/jscent.js
Labels: enhancement

#50 Wallaby.js installation and running
  wallaby.js
Labels: enhancement
